apiVersion: v1
kind: Service
metadata:
  name: istio-pilot-ilb
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "istio-pilot.example.com, istio-pilot.istio-system.example.com"
    service.beta.kubernetes.io/aws-load-balancer-internal: 10.0.0.0/8
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    istio: pilot
spec:
  type: LoadBalancer
  ports:
  - name: https-pilot
    port: 15005
    protocol: TCP
  - port: 8080
    name: http-pilot
    protocol: TCP
  - port: 15010
    name: grpc-pilot
    protocol: TCP
  - port: 15011
    name: tls-grpc-pilot
    protocol: TCP
  selector:
    istio: pilot
---
apiVersion: v1
kind: Service
metadata:
  name: citadel-ilb
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "istio-citadel.example.com"
    service.beta.kubernetes.io/aws-load-balancer-internal: 10.0.0.0/8
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    istio: citadel
spec:
  type: LoadBalancer
  ports:
  - port: 8060
    protocol: TCP
  selector:
    istio: citadel
